# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Gohugo Default Theme"
license = "MIT"
licenselink = "https://github.com/budparr/gohugo-default-theme/blob/master/LICENSE.md"
description = "A Base theme for building full featured Hugo sites"
homepage = "https://github.com/budparr/gohugo-default-theme"
tags = ["website", "starter"]
features = ["posts", ""]
min_version = 0.18

[author]
  name = "Bud Parr"
  homepage = "https://github.com/budparr"
